# Fluency
filled_pauses = {
    "en": [
        "uhm",
        "uh",
        "uhummm",
        "hum",
        "hummmm",
        "humm",
        "mm",
        "mmm",
        "Mm",
        "um",
        "hmmm",
        "hmm",
        "hm",
        "eh",
        "err",
    ],
    "fr": ["euh", "hum", "heu", "hm", "öhm", "uhm", "mmh", "mh"],
    "ucsf": ["um", "er", "uh", "ah", "hmm", "erm", "like", "so", "well"],
}

# context fragments computation
target_words = {
    "en": [
        ("the", "there"),
        ("dry", "or"),
        ("out", "outside"),
        ("wash", "drying"),
        ("curt", "the"),
        ("is", "spill"),
        ("wash", "is"),
        ("bow", "Cup"),
        ("tap", "taps"),
        ("spill", "is"),
        ("kit", "the"),
        ("stand", "standing"),
        ("go", "reaching"),
        ("dish", "The"),
        ("look", "uh"),
        ("dry", "or"),
        ("watch", "washing"),
        ("sleeve", "sleeveless"),
        ("cook", "cookie"),
        ("a", "an"),
        ("day", "daytime"),
        ("curt", "the"),
        ("look", "reaching"),
        ("sister", "reach"),
        ("cab", "the"),
        ("cook", "the"),
        ("stand", "climbing"),
        ("her", "ask"),
        ("ask", "asking"),
        ("up", "upper"),
    ],
}
