# ICU dictionaries for both languages
ICU_cookie_fr = {
    "mère": ["mère", "maman", "mamie", "mam", "mamma", "momma", "ma", "mama", "femme"],
    "garçon": [
        "garçon",
        "gamin",
        "mec",
        "gosse",
        "fils",
        "écolier",
        "jeune homme",
        "jeune garçon",
        "enfant mâle",
    ],
    "fille": [
        "fille",
        "fille",
        "jeune fille",
        "écolière",
        "jeune dame",
        "jeune fille",
        "enfant femelle",
    ],
    "cuisine": [
        "cuisine",
    ],
    "extérieur": ["extérieur", "dehors", "à l'air libre", "en plein air"],
    "robinet": ["robinet", "évacuation", "mitigeur"],
    "eau": [
        "eau",
    ],
    "évier": [
        "évier",
    ],
    "sol": ["sol", "terre", "plancher"],
    "assiette": ["assiette", "plat", "plateau", "soucoupe"],
    "vaisselle_sur_comptoir": ["posée sur", "placée sur", "étalée sur"],
    "comptoir": ["comptoir", "plan de travail"],
    "cookies": ["cookies", "biscuit", "biscuits"],
    "bocal": ["bocal", "pot", "boîte"],
    "placard": ["placard", "armoire", "placards", "armoires"],
    "tabouret": ["tabouret", "escabeau"],
    "fenêtre": [
        "fenêtre",
    ],
    "rideau": ["rideau", "store", "écran", "volet"],
    "garçon_prenant_cookie": [
        "prenant",
        "saisissant",
        "atteignant",
        "prendre",
        "saisir",
        "atteindre",
        "se saisir",
    ],
    "garçon_tabouret_tombant": ["tombant", "basculant", "tomber", "basculer"],
    "mère_séchant_lavant_vaisselle": [
        "sécher",
        "séchant",
        "laver",
        "lavant",
        "nettoyer",
        "nettoyant",
        "frotter",
        "frottant",
        "essuyant",
        "faire la vaisselle",
    ],
    "eau_débordant": [
        "déborder",
        "débordant",
        "renverser",
        "renversant",
        "cascader",
        "évier débordant",
        "débordement",
    ],
    "fille_demandant_cookie": [
        "demander",
        "demandant",
        "vouloir",
        "veut",
        "solliciter",
        "sollicite",
    ],
    "mère_indifférente_au_débordement": [
        "indifférente",
        "pas dérangée",
        "se soucier",
        "pas dérangé",
        "remarqué",
        "déranger",
    ],
    "mère_ne_remarquant_pas_les_enfants": [
        "inconsciente",
        "remarqué",
        "pas remarqué",
        "pas prendre garde",
        "pas dérangée",
        "pas dérangé",
    ],
}

ICU_cookie_en = {
    "mother": [
        "mother",
        "mom",
        "mum",
        "mommy",
        "mummy",
        "mamma",
        "momma",
        "ma",
        "mama",
        "woman",
    ],
    "boy": [
        "boy",
        "guy",
        "dude",
        "lad",
        "son",
        "schoolboy",
        "young man",
        "son",
        "young boy",
        "male child",
    ],
    "girl": [
        "girl",
        "daughter",
        "lass",
        "schoolgirl",
        "young lady",
        "young girl",
        "female child",
    ],
    "kitchen": [
        "kitchen",
    ],
    "exterior": ["exterior", "outside", "outdoor", "outdoors"],
    "faucet": ["faucet", "drain", "tap"],
    "water": [
        "water",
    ],
    "sink": [
        "sink",
    ],
    "floor": ["floor", "ground", "flooring"],
    "plate": ["plate", "dish", "platter", "saucer"],
    "dishes on counter": ["laying on", "placed on", "spread on"],
    "counter": ["counter", "worktop", "counter top", "countertop"],
    "cookies": ["cookies", "cookie", "biscuits", "biscuit"],
    "jar": ["jar", "pot", "tin"],
    "cabinet": ["cabinet", "cupboard", "cabinets", "cupboards"],
    "stool": ["stool", "footstool"],
    "window": [
        "window",
    ],
    "curtain": ["curtain", "blind", "screen", "shutter"],
    "boy_taking_cookie": [
        "taking",
        "grabbing",
        "reaching",
        "take",
        "grab",
        "reach",
        "get hold",
    ],
    "boy_stool_falling": ["falling", "tipping", "fall", "tip"],
    "mother_drying_washing_dishes": [
        "dry",
        "drying",
        "wash",
        "washing",
        "clean",
        "cleaning",
        "scrub",
        "scrubbing",
        "wiping",
        "doing dishes",
        "doing the dishes",
    ],
    "water_overflowing": [
        "overflow",
        "overflowing",
        "spill",
        "spilling",
        "cascading",
        "sink running over",
        "overrunning",
    ],
    "girl_asking_for_cookie": [
        "ask",
        "asking",
        "want",
        "wants",
        "requesting",
        "requests",
    ],
    "mother_unconcerned_about_overflowing": [
        "unconcerned",
        "unbothered",
        "care",
        "not bothered",
        "noticed",
        "bother",
    ],
    "mother_not_noticing_children": [
        "unnoticing",
        "noticed",
        "not noticed",
        "not take notice",
        "unbothered",
        "not bothered",
    ],
}

# define Information Content Units (ICU) with the grid from Jensen, Chenery, Copland (2006) J Comm Dis
ICU_picnic_en = {
    "father": ["father", "husband", "daddy", "Dad", "dad"],
    "mother": ["mother", "wife", "mom", "mommy", "girl"],
    "couple": ["couple", "parents", "owners"],
    "child": [
        "child",
    ],
    "boy": ["boy", "brother"],
    "fisherman": ["fisherman", "fisher", "rod"],
    "sailors": ["sailors", "people", "people sailing"],
    "dog": ["dog", "doggy", "animal"],
    "garage": [
        "garage",
    ],
    "water": [
        "water",
        "lake",
        "river",
        "sea",
        "ocean",
        "bank",
        "edge",
        "shore",
        "riverside",
    ],
    "beach": ["beach", "sand"],
    #'pail': ['pail', 'blanket'], this one is not in Jensen
    "jetty": ["jetty", "wharf", "dock"],
    "kite": [
        "kite",
    ],
    "book": ["book", "novel"],
    "bucket": [
        "bucket",
    ],
    "spade": ["spade", "shovel"],
    "car": ["car", "vehicle", "automobile", "sedan", "wagon"],
    "boat": ["boat", "sailboat", "yacht", "vessel", "slinghy", "sloop"],
    "flag": ["flag", "pole"],
    "radio": ["radio", "transistor"],
    "sandals": ["sandals", "shoes", "shoe", "flip", "flops"],
    "tree": ["tree", "oak"],
    "basket": ["basket"],
    "drink": ["drink", "bottle", "wine", "soda", "beer", "liquor", "coffee", "tea"],
    "house": ["house", "cottage", "shack", "cottage"],
    "reading": ["reading", "read"],
    "fishing": ["fishing", "fish", "catch"],
    "pouring": ["pouring", "pour", "serve"],
    "flying": ["flying", "fly"],  # flag #kite
    "playing": [
        "playing",
        "play",
        "build",
        "building",
        "blasting",
    ],  # child on the beach # radio
    "picnicking": ["picnic", "picnicking"],
    "sailing": ["sailing", "sail", "boating"],
    "parking": ["parking", "parked", "park"],
}

ICU_references = {
    "cookie_en": ICU_cookie_en,
    "cookie_fr": ICU_cookie_fr,
    "picnic_en": ICU_picnic_en,
}
