name: Deploy Docs

on:
  push:
    branches: ['main']
    paths: ['docs/**']

jobs:
  build-deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: docs
        run: make install

      - name: Build and deploy to GitHub Pages
        working-directory: docs
        run: make deploy
